apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: dpso
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "riccardobusetti/spark:1.0"
  imagePullPolicy: Always
  mainClass: MainKt
  mainApplicationFile: "local:///opt/spark/jars/dpso.jar"
  arguments:
    - "sync"
    - "10"
    - "5"
    - "2"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1